Add QT_RENDER_TYPE
deepin-community/qt6-base pull request #16
Opened 2024-09-12 09:10 UTC by Dami-star

The user can set QT_RENDER_TYPE to OpenGL or OpenGLES. The default value is OpenGL. No longer need to reconfigure the compilation parameter es2 opengl.

2024-09-12 09:19 UTC, zccrs commented on debian/patches/add-QT_RENDER_TYPE.patch
> ++    QString renderType = QString::fromLocal8Bit(qgetenv("QT_RENDER_TYPE"));
Use `QT_FORCE_OPENGL_TYPE`

2024-09-12 09:29 UTC, Dami-star commented on debian/patches/add-QT_RENDER_TYPE.patch
> ++    QString renderType = QString::fromLocal8Bit(qgetenv("QT_RENDER_TYPE"));
done

2024-09-12 09:49 UTC, zccrs requested changes

2024-09-12 09:49 UTC, zccrs commented on debian/patches/series
> +add-QT_RENDER_TYPE.patch
patch file name

2024-09-12 09:52 UTC, Dami-star commented on debian/patches/series
> +add-QT_RENDER_TYPE.patch
done

2024-09-12 09:54 UTC, zccrs approved these changes

2024-09-18 02:20 UTC, Dami-star commented
/integrate

2024-09-18 02:45 UTC, Zeno-sole commented
/integrate

2024-09-19 08:30 UTC, merged